---
- name: Create fleuntd services
  hosts: linux_servers


  vars:
   ansible_python_interpreter: /bin/python3

  tasks:
  - name: Install Docker SDK for Python
    pip:
      name: "docker<5" 

  - name: Get infos on container
    docker_container_info:
      name: jenkins/jenkins
    register: result

  - name: Does container exist?
    debug:
      msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

  - name: Print the status of the container
    debug:
      msg: "The container status is {{ result.container['State']['Status'] }}"

