---
- name: Loop Playbook
  hosts: linux_servers
  become: yes

  tasks:
  - name: Check and Print LINUX Version
    debug: var=ansible_os_family

  - name: "Say hello to ALL"
    debug: msg="Hello {{ item }}"
    loop:
        - "Vasya"
        - "Petya"
        - "Masha"
        - "Olya"

  - name: Loop Until example
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("ZZZZ") == false

  - name: Print Final Output
    debug:
      var: output.stdout

  - name: Install many packeges
    yum: name={{ item }} state=installed
    with_items:
       - mc
       - tree
    when: ansible_os_family == "RedHat"
