---
- name: Install python in target node with ansible
  hosts: canary
  become: true
  gather_facts: no
  pre_tasks:
  - name: install python
    raw: 'cat < /root/ansible/script.sh'
    args:
      executable: /bin/bash
