---
# tasks file for install_jenkins

- name: Pull and run Docker image with Jenkins
  docker_container:
    name: Jenkins
    image: jenkins/jenkins:2.307
    state: started
    ports:
     - "8080:8080"
     - "50000:50000"
